[package]
name = "quad-gl"
version = "0.1.0"
authors = ["not-fl3 <not.fl3@gmail.com>"]
edition = "2018"

[dependencies]
miniquad = "0.2"
glam = "*"
image = { version = "0.22", default-features = false, features = ["png_codec"] }